/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.petshop.view;

import javax.swing.UIManager;

/**
 *
 * @author danilo
 */
public class GerenciamentoAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciamentoAnimal
     */
    public GerenciamentoAnimal() {
        initComponents();
         try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome_animal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        iddono_animal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        raca_animal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        especie_animal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        codigo_animal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idade_animal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(530, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));
        getContentPane().add(nome_animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 179, -1));

        jLabel2.setText("Dono");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        iddono_animal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(iddono_animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 78, 200, -1));

        jLabel3.setText("Raça");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));

        raca_animal.setText("jTextField2");
        getContentPane().add(raca_animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, 179, -1));

        jLabel4.setText("Espécie");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));
        getContentPane().add(especie_animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 124, 200, -1));

        jLabel5.setText("Código");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        codigo_animal.setText("codigo_animal");
        getContentPane().add(codigo_animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        jLabel6.setText("Idade");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(idade_animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 179, -1));

        jLabel7.setText("Observação");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, -1, -1));

        jScrollPane1.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, 474, -1));

        jButton1.setText("Salvar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jButton2.setText("Limpar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 340, -1, -1));

        jButton3.setText("Editar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 340, -1, -1));

        jButton4.setText("Excluir");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 340, -1, -1));

        jButton5.setText("Sair");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 340, -1, -1));

        jLabel8.setText("Sexo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 150, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 170, 201, -1));

        jScrollPane2.setBorder(null);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 381, 480, 156));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo_animal;
    private javax.swing.JTextField especie_animal;
    private javax.swing.JTextField idade_animal;
    private javax.swing.JComboBox<String> iddono_animal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nome_animal;
    private javax.swing.JTextField raca_animal;
    // End of variables declaration//GEN-END:variables
}
